# Generated by Django 5.1.3 on 2024-12-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_profile_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
    ]
