# Generated by Django 5.1.3 on 2025-04-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_cartorder_customer_remove_cartorder_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider/')),
                ('alt_text', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
